name: example
description: Example app showcasing how to use the funvas package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  funvas:
    # When depending on this package from a real application you should use:
    #   funvas: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  golden_toolkit: ^0.9.0-nullsafety.0

  pedantic: ^1.10.0-nullsafety.3

flutter:
  uses-material-design: true

  assets:
    # See https://github.com/eBay/flutter_glove_box/issues/31.
    - assets/stub/
