name: funvas
description: >2-
  Package for creating canvas animations based on time and math functions.

  Fun + canvas -> funvas :)
version: 0.1.0-nullsafety.0
repository: https://github.com/creativecreatorormaybenot/funvas

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.10.0-nullsafety.3
