name: open_simplex_2
description: Dart implementation of KdotJPG's OpenSimplex2 noise algorithms.
version: 0.0.1
homepage: https://github.com/creativecreatorormaybenot/funvas/tree/main/open_simplex_2

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
