name: funvas_tweets
description: Collection of funvas animations tweeted @creativemaybeno.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  funvas:
    path: ../funvas

  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0

flutter:
  uses-material-design: true
