name: funvas_tweets
description: Collection of funvas animations tweeted @creativemaybeno.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.14.0-0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  funvas:
    path: ../funvas

  google_fonts: ^2.3.1
  open_simplex_2:
    path: ../open_simplex_2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true
