name: funvas_demo
description: Demonstration application for the funvas package, allowing to explore some animations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3

flutter:
  uses-material-design: true
