name: funvas
description: >2-
  Package for creating canvas animations based on time and math functions.

  Fun + canvas -> funvas :)
version: 0.1.7
homepage: https://github.com/creativecreatorormaybenot/funvas/tree/main/funvas

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
