name: funvas
description: >2-
  Package for creating canvas animations based on time and math functions.

  Fun + canvas -> funvas :)
version: 0.1.2
homepage: https://github.com/creativecreatorormaybenot/funvas/tree/master/funvas

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: 1.10.0
