name: funvas
description: >2-
  Package for creating canvas animations based on time and math functions.

  Fun + canvas -> funvas :)
version: 0.1.3+3
homepage: https://github.com/creativecreatorormaybenot/funvas/tree/master/funvas

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.3
