name: pana

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/publish.yml'
      - 'funvas/pubspec.yaml'
      - 'open_simplex_2/pubspec.yaml'

jobs:
  configure:
    timeout-minutes: 9
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} configuration
    strategy:
      matrix:
        package:
          - 'funvas'
          - 'open_simplex_2'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: axel-op/dart-package-analyzer@v3
        with:
          relativePath: ${{ matrix.package }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
