name: Publish

on:
  push:
    branches:
      - master

jobs:
  pana:
    timeout-minutes: 9
    runs-on: ubuntu-latest
    name: Configuration of funvas

    steps:
      - uses: actions/checkout@v2.3.3
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: pana
    timeout-minutes: 4
    runs-on: ubuntu-latest
    name: Publishing of funvas

    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 2

      - name: Check package Pubspec
        id: pubspec
        run: |
          set +e
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep 'pubspec.yaml' &> /dev/null
          echo ::set-output name=changed::$?
          set -e
      - name: Extract package version
        if: steps.pubspec.outputs.changed == 0
        run: |
          echo ::set-env name=VERSION::"$(awk '{if ($1 ~ /^version:/) print $2}' pubspec.yaml)"
      - uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        if: steps.pubspec.outputs.changed == 0
        with:
          credential: ${{ secrets.PUB_CREDENTIALS }}
          flutter_package: true
          skip_test: true
      - name: Create Release
        if: steps.pubspec.outputs.changed == 0
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: funvas v${{ env.VERSION }}
          draft: false
          prerelease: false
