name: gallery

on:
  push:
    branches:
      - main
    paths:
      - 'funvas_gallery/lib/**'
      - 'funvas_gallery/web/**'
      - 'funvas_gallery/pubspec.yaml'
      - 'funvas_tweets/lib/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    name: deployment

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'beta'

      - name: Build gallery web app
        run: |
          cd funvas_gallery
          flutter pub get
          flutter config --enable-web
          flutter build web --no-sound-null-safety --web-renderer canvaskit
          cd build/web
          touch ".nojekyll"
          echo "funvas.creativemaybeno.dev" > CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: funvas_gallery/build/web
          GIT_CONFIG_NAME: creativecreatorormaybenot
          GIT_CONFIG_EMAIL: creativecreatorormaybenot@gmail.com
          COMMIT_MESSAGE: Deploy funvas gallery app
